# This is a basic workflow to help you get started with Actions

name: Build and Deploy github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: deploy
        run: |
          npm ci
          npm run build --if-present
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name "gatosyocora"
          git remote set-url origin https://gatosyocora:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
